site_name: My Docs
repo_url: https://github.com/migueldefrias/MiguelDeFrias.git
repo_name: MiguelDeFrias

theme:
  icon:
   repo: fontawesome/brands/git-alt
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: teal
      accent: green
    - scheme: slate 
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode    
      primary: teal
      accent: blue

nav:
  - Página Inicial: index.md