site_name: Miguel de Frias
repo_url: https://migueldefrias.git
repo_name: MiguelDeFrias

theme:
  icon: 
   repo: 
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  language: eng
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: blue
      accent: blue  
    - scheme: slate 
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode    
      primary: dark blue
      accent: yellow

nav:
  - Introduction: index.md
